/*Hdeste70 FIX Orgirmar Grunt gossip menus */

UPDATE `creature_template` SET `entry`='3296', `difficulty_entry_1`='0', `difficulty_entry_2`='0', `difficulty_entry_3`='0', `KillCredit1`='0', `KillCredit2`='0', `name`='Orgrimmar Grunt', `femaleName`='', `subname`='', `TitleAlt`=NULL, `IconName`='Directions', `gossip_menu_id`='1951', `minlevel`='120', `maxlevel`='120', `HealthScalingExpansion`='0', `RequiredExpansion`='0', `VignetteID`='0', `faction`='85', `npcflag`='1', `speed_walk`='1', `speed_run`='1.14286', `scale`='1', `rank`='0', `dmgschool`='0', `BaseAttackTime`='2000', `RangeAttackTime`='0', `BaseVariance`='0', `RangeVariance`='0', `unit_class`='1', `unit_flags`='32768', `unit_flags2`='2048', `unit_flags3`='0', `dynamicflags`='0', `family`='0', `trainer_type`='0', `trainer_class`='0', `trainer_race`='0', `type`='7', `type_flags`='0', `type_flags2`='0', `lootid`='0', `pickpocketloot`='3296', `skinloot`='0', `resistance1`='0', `resistance2`='0', `resistance3`='0', `resistance4`='0', `resistance5`='0', `resistance6`='0', `spell1`='8599', `spell2`='0', `spell3`='0', `spell4`='0', `spell5`='0', `spell6`='0', `spell7`='0', `spell8`='0', `VehicleId`='0', `mingold`='0', `maxgold`='0', `AIName`='SmartAI', `MovementType`='0', `InhabitType`='3', `HoverHeight`='1', `HealthModifier`='1.5', `HealthModifierExtra`='1', `ManaModifier`='1', `ManaModifierExtra`='1', `ArmorModifier`='1', `DamageModifier`='1', `ExperienceModifier`='1', `RacialLeader`='0', `movementId`='0', `FadeRegionRadius`='0', `WidgetSetID`='0', `WidgetSetUnitConditionID`='0', `RegenHealth`='1', `mechanic_immune_mask`='0', `flags_extra`='32768', `ScriptName`='', `VerifiedBuild`='28153' WHERE (`entry`='3296');
UPDATE `gossip_menu` SET `MenuId`='1951', `TextId`='2593', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`TextId`='2593');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='0', `OptionIcon`='0', `OptionText`='Battle Pet Trainer', `OptionBroadcastTextId`='67342', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='0');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='2', `OptionIcon`='0', `OptionText`='Transmogrification', `OptionBroadcastTextId`='56155', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='2');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='3', `OptionIcon`='0', `OptionText`='Void Storage', `OptionBroadcastTextId`='53080', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='3');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='4', `OptionIcon`='0', `OptionText`='Auction House', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='4');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='5', `OptionIcon`='0', `OptionText`='Bank', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='5');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='6', `OptionIcon`='0', `OptionText`='Barber', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='6');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='7', `OptionIcon`='0', `OptionText`='Battlemasters', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='7');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='8', `OptionIcon`='0', `OptionText`='Class Trainer', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='8');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='9', `OptionIcon`='0', `OptionText`='Flight Master', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='9');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='10', `OptionIcon`='0', `OptionText`='Guild Master & Vendor', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='10');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='11', `OptionIcon`='0', `OptionText`='Inn', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='11');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='12', `OptionIcon`='0', `OptionText`='Officer\'s Lounge', `OptionBroadcastTextId`='9749', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='12');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='13', `OptionIcon`='0', `OptionText`='Other Continents', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='13');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='14', `OptionIcon`='0', `OptionText`='Profession Trainer', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='14');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='15', `OptionIcon`='0', `OptionText`='Stable Master', `OptionBroadcastTextId`='0', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='15');
UPDATE `gossip_menu_option` SET `MenuId`='1951', `OptionIndex`='16', `OptionIcon`='0', `OptionText`='Zeppelin Master', `OptionBroadcastTextId`='5518', `OptionType`='1', `OptionNpcFlag`='1', `VerifiedBuild`='27404' WHERE (`MenuId`='1951') AND (`OptionIndex`='16');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='0', `ActionMenuId`='14951', `ActionPoiId`='12888' WHERE (`MenuId`='1951') AND (`OptionIndex`='0');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='2', `ActionMenuId`='12246', `ActionPoiId`='12527' WHERE (`MenuId`='1951') AND (`OptionIndex`='2');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='3', `ActionMenuId`='12246', `ActionPoiId`='12527' WHERE (`MenuId`='1951') AND (`OptionIndex`='3');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='4', `ActionMenuId`='12639', `ActionPoiId`='0' WHERE (`MenuId`='1951') AND (`OptionIndex`='4');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='5', `ActionMenuId`='12638', `ActionPoiId`='0' WHERE (`MenuId`='1951') AND (`OptionIndex`='5');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='6', `ActionMenuId`='10018', `ActionPoiId`='12276' WHERE (`MenuId`='1951') AND (`OptionIndex`='6');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='7', `ActionMenuId`='8224', `ActionPoiId`='12012' WHERE (`MenuId`='1951') AND (`OptionIndex`='7');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='8', `ActionMenuId`='1949', `ActionPoiId`='0' WHERE (`MenuId`='1951') AND (`OptionIndex`='8');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='9', `ActionMenuId`='1902', `ActionPoiId`='10268' WHERE (`MenuId`='1951') AND (`OptionIndex`='9');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='10', `ActionMenuId`='1903', `ActionPoiId`='10269' WHERE (`MenuId`='1951') AND (`OptionIndex`='10');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='11', `ActionMenuId`='12637', `ActionPoiId`='0' WHERE (`MenuId`='1951') AND (`OptionIndex`='11');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='12', `ActionMenuId`='5882', `ActionPoiId`='11468' WHERE (`MenuId`='1951') AND (`OptionIndex`='12');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='13', `ActionMenuId`='12245', `ActionPoiId`='0' WHERE (`MenuId`='1951') AND (`OptionIndex`='13');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='14', `ActionMenuId`='1942', `ActionPoiId`='0' WHERE (`MenuId`='1951') AND (`OptionIndex`='14');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='15', `ActionMenuId`='4902', `ActionPoiId`='10848' WHERE (`MenuId`='1951') AND (`OptionIndex`='15');
UPDATE `gossip_menu_option_action` SET `MenuId`='1951', `OptionIndex`='16', `ActionMenuId`='9727', `ActionPoiId`='0' WHERE (`MenuId`='1951') AND (`OptionIndex`='16');
       