UPDATE `creature_template` SET `scriptname` = "" WHERE `scriptname` = "npc_warl_chaos_tear";
UPDATE `creature_template` SET `scriptname` = "" WHERE `scriptname` = "npc_warl_shadowy_tear";
UPDATE `creature_template` SET `scriptname` = "" WHERE `scriptname` = "npc_arti_priest_void_tendril";

DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_dru_new_moon";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_dru_half_moon";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_dru_full_moon";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_dru_ashamane_frenzy";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "aura_arti_dru_ashamane_frenzy";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_mage_immolation";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_mage_phoenix_flames";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_mage_phoenix_flames_trigger";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_sha_servant_of_the_queen";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_sha_caress_of_the_tidemother";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_warl_deadwind_harvest";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_warl_reap_souls";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_warl_dimensional_rift";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_warl_thalkiels_consumption";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_mage_ebonbolt";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_pri_call_of_the_void";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_pal_tyr_deliverance";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "aura_artifact_shaman_stormkeeper";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "aura_artifact_hunter_broken_bond";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_hun_titans_thunder";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "aura_arti_hun_titans_thunder";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "aura_concordance_of_the_legionfall";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_pri_thrive";
DELETE FROM `spell_script_names` WHERE `ScriptName`= "spell_arti_pri_sphere_of_insanity_summon";