-- mogu_shan_palace
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_glintrok_hexxer' where `entry`= 61216; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_glintrok_skulker' where `entry`= 61240; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_glintrok_ironhide' where `entry`= 61242; 
update `creature_template` set `AIName`= '', `ScriptName`= 'boss_gekkan' where `entry`= 61243; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_glintrok_ironhide' where `entry`= 61337; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_glintrok_skulker' where `entry`= 61338; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_glintrok_oracle' where `entry`= 61339; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_glintrok_hexxer' where `entry`= 61340; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_mp_quilen_guardian' where `entry`= 61387; 
update `creature_template` set `AIName`= '', `ScriptName`= 'boss_xin_the_weaponmaster' where `entry`= 61398; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_glintrok_scout_2' where `entry`= 61399; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_animated_staff' where `entry`= 61433; 
update `creature_template` set `AIName`= '', `ScriptName`= 'boss_kuai_the_brute' where `entry`= 61442; 
update `creature_template` set `AIName`= '', `ScriptName`= 'boss_ming_the_cunning' where `entry`= 61444; 
update `creature_template` set `AIName`= '', `ScriptName`= 'boss_haiyan_the_unstoppable' where `entry`= 61445; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_adepts' where `entry`= 61447; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_adepts' where `entry`= 61449; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_adepts' where `entry`= 61450; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_animated_axe' where `entry`= 61451; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_mu_shiba' where `entry`= 61453; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_fire_ring_trigger' where `entry`= 61499; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_adepts' where `entry`= 61549; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_adepts' where `entry`= 61550; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_adepts' where `entry`= 61551; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_whirling_dervish' where `entry`= 61626; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_xian_the_weaponmaster_trigger' where `entry`= 61884; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_faintly_glowing_gem' where `entry`= 63808; 
update `creature_template` set `AIName`= '', `ScriptName`= 'npc_glintrok_scout' where `entry`= 64243; 


DELETE FROM `spell_script_names` WHERE `spell_id`=119076 AND `ScriptName`='spell_saurok_help_call';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119076, 'spell_saurok_help_call');
DELETE FROM `spell_script_names` WHERE `spell_id`=119311 AND `ScriptName`='spell_dart';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119311, 'spell_dart');
DELETE FROM `spell_script_names` WHERE `spell_id`=119311 AND `ScriptName`='spell_dart_damage';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119311, 'spell_dart_damage');
DELETE FROM `spell_script_names` WHERE `spell_id`=119314 AND `ScriptName`='spell_dart';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119314, 'spell_dart');
DELETE FROM `spell_script_names` WHERE `spell_id`=119337 AND `ScriptName`='spell_dart';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119337, 'spell_dart');
DELETE FROM `spell_script_names` WHERE `spell_id`=119338 AND `ScriptName`='spell_dart';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119338, 'spell_dart');
DELETE FROM `spell_script_names` WHERE `spell_id`=119684 AND `ScriptName`='spell_groundslam_xin';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119684, 'spell_groundslam_xin');
DELETE FROM `spell_script_names` WHERE `spell_id`=119922 AND `ScriptName`='spell_shockwave_kuai';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119922, 'spell_shockwave_kuai');
DELETE FROM `spell_script_names` WHERE `spell_id`=119922 AND `ScriptName`='spell_shockwave_kuai_eff';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119922, 'spell_shockwave_kuai_eff');
DELETE FROM `spell_script_names` WHERE `spell_id`=119929 AND `ScriptName`='spell_shockwave_kuai_eff';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119929, 'spell_shockwave_kuai_eff');
DELETE FROM `spell_script_names` WHERE `spell_id`=119931 AND `ScriptName`='spell_shockwave_kuai_eff';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119931, 'spell_shockwave_kuai_eff');
DELETE FROM `spell_script_names` WHERE `spell_id`=119932 AND `ScriptName`='spell_shockwave_kuai_eff';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119932, 'spell_shockwave_kuai_eff');
DELETE FROM `spell_script_names` WHERE `spell_id`=119933 AND `ScriptName`='spell_shockwave_kuai_eff';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119933, 'spell_shockwave_kuai_eff');
DELETE FROM `spell_script_names` WHERE `spell_id`=119982 AND `ScriptName`='spell_whirling_dervish';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119982, 'spell_whirling_dervish');
DELETE FROM `spell_script_names` WHERE `spell_id`=119994 AND `ScriptName`='spell_whirling_dervish_knock';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (119994, 'spell_whirling_dervish_knock');
DELETE FROM `spell_script_names` WHERE `spell_id`=120100 AND `ScriptName`='spell_magnetic_field';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120100, 'spell_magnetic_field');
DELETE FROM `spell_script_names` WHERE `spell_id`=120102 AND `ScriptName`='spell_magnetic_pull';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120102, 'spell_magnetic_pull');
DELETE FROM `spell_script_names` WHERE `spell_id`=120118 AND `ScriptName`='spell_magnetic_pull';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120118, 'spell_magnetic_pull');
DELETE FROM `spell_script_names` WHERE `spell_id`=120119 AND `ScriptName`='spell_magnetic_pull';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120119, 'spell_magnetic_pull');
DELETE FROM `spell_script_names` WHERE `spell_id`=120124 AND `ScriptName`='spell_crossbow_xin';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120124, 'spell_crossbow_xin');
DELETE FROM `spell_script_names` WHERE `spell_id`=120142 AND `ScriptName`='spell_dart';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120142, 'spell_dart');
DELETE FROM `spell_script_names` WHERE `spell_id`=120165 AND `ScriptName`='spell_haiyan_conflagrate_aura';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120165, 'spell_haiyan_conflagrate_aura');
DELETE FROM `spell_script_names` WHERE `spell_id`=120167 AND `ScriptName`='spell_haiyan_conflagrate_targeting';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120167, 'spell_haiyan_conflagrate_targeting');
DELETE FROM `spell_script_names` WHERE `spell_id`=120194 AND `ScriptName`='spell_haiyan_meteor_targeting';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120194, 'spell_haiyan_meteor_targeting');
DELETE FROM `spell_script_names` WHERE `spell_id`=120196 AND `ScriptName`='spell_haiyan_meteor';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120196, 'spell_haiyan_meteor');
DELETE FROM `spell_script_names` WHERE `spell_id`=120444 AND `ScriptName`='spell_xin_mogu_jump_targeting';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120444, 'spell_xin_mogu_jump_targeting');
DELETE FROM `spell_script_names` WHERE `spell_id`=120499 AND `ScriptName`='spell_shockwave_targeting';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (120499, 'spell_shockwave_targeting');
DELETE FROM `spell_script_names` WHERE `spell_id`=123127 AND `ScriptName`='spell_dart';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (123127, 'spell_dart');
DELETE FROM `spell_script_names` WHERE `spell_id`=123128 AND `ScriptName`='spell_dart';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (123128, 'spell_dart');
DELETE FROM `spell_script_names` WHERE `spell_id`=124320 AND `ScriptName`='spell_dart';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (124320, 'spell_dart');
DELETE FROM `spell_script_names` WHERE `spell_id`=124321 AND `ScriptName`='spell_dart';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (124321, 'spell_dart');
DELETE FROM `spell_script_names` WHERE `spell_id`=124531 AND `ScriptName`='spell_activate_blades';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (124531, 'spell_activate_blades');
DELETE FROM `spell_script_names` WHERE `spell_id`=124534 AND `ScriptName`='spell_activate_blades';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (124534, 'spell_activate_blades');
DELETE FROM `spell_script_names` WHERE `spell_id`=124540 AND `ScriptName`='spell_turn_off_blades';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (124540, 'spell_turn_off_blades');
