DELETE FROM `scene_template` WHERE `SceneId`=28;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (28, 0, 179, '');
DELETE FROM `scene_template` WHERE `SceneId`=29;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (29, 0, 176, '');
DELETE FROM `scene_template` WHERE `SceneId`=30;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (30, 0, 181, '');
DELETE FROM `scene_template` WHERE `SceneId`=34;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (34, 0, 178, '');
DELETE FROM `scene_template` WHERE `SceneId`=38;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (38, 0, 180, '');
DELETE FROM `scene_template` WHERE `SceneId`=39;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (39, 0, 67, '');
DELETE FROM `scene_template` WHERE `SceneId`=40;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (40, 0, 177, '');
DELETE FROM `scene_template` WHERE `SceneId`=41;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (41, 0, 182, '');
DELETE FROM `scene_template` WHERE `SceneId`=43;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (43, 0, 174, '');
DELETE FROM `scene_template` WHERE `SceneId`=46;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (46, 1, 190, '');
DELETE FROM `scene_template` WHERE `SceneId`=71;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (71, 0, 208, '');
DELETE FROM `scene_template` WHERE `SceneId`=86;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (86, 0, 234, '');
DELETE FROM `scene_template` WHERE `SceneId`=93;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (93, 4, 245, '');
DELETE FROM `scene_template` WHERE `SceneId`=106;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (106, 1, 147, '');
DELETE FROM `scene_template` WHERE `SceneId`=127;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (127, 0, 285, '');
DELETE FROM `scene_template` WHERE `SceneId`=128;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (128, 0, 286, '');
DELETE FROM `scene_template` WHERE `SceneId`=129;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (129, 0, 287, '');
DELETE FROM `scene_template` WHERE `SceneId`=130;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (130, 0, 291, '');
DELETE FROM `scene_template` WHERE `SceneId`=136;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (136, 1, 299, '');
DELETE FROM `scene_template` WHERE `SceneId`=137;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (137, 0, 300, '');
DELETE FROM `scene_template` WHERE `SceneId`=152;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (152, 0, 315, '');
DELETE FROM `scene_template` WHERE `SceneId`=153;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (153, 8, 316, '');
DELETE FROM `scene_template` WHERE `SceneId`=156;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (156, 0, 319, '');
DELETE FROM `scene_template` WHERE `SceneId`=157;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (157, 0, 320, '');
DELETE FROM `scene_template` WHERE `SceneId`=158;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (158, 0, 321, '');
DELETE FROM `scene_template` WHERE `SceneId`=167;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (167, 4, 391, '');
DELETE FROM `scene_template` WHERE `SceneId`=169;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (169, 0, 398, '');
DELETE FROM `scene_template` WHERE `SceneId`=171;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (171, 0, 402, '');
DELETE FROM `scene_template` WHERE `SceneId`=172;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (172, 0, 403, '');
DELETE FROM `scene_template` WHERE `SceneId`=173;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (173, 0, 404, '');
DELETE FROM `scene_template` WHERE `SceneId`=175;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (175, 0, 410, '');
DELETE FROM `scene_template` WHERE `SceneId`=178;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (178, 0, 414, '');
DELETE FROM `scene_template` WHERE `SceneId`=186;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (186, 9, 447, '');
DELETE FROM `scene_template` WHERE `SceneId`=190;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (190, 0, 450, '');
DELETE FROM `scene_template` WHERE `SceneId`=191;                                                        
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (191, 0, 451, '');
DELETE FROM `scene_template` WHERE `SceneId`=194;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (194, 0, 454, '');
DELETE FROM `scene_template` WHERE `SceneId`=208;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (208, 20, 476, '');
DELETE FROM `scene_template` WHERE `SceneId`=210;                                                         
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (210, 20, 497, '');
DELETE FROM `scene_template` WHERE `SceneId`=218;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (218, 0, 218, '');
DELETE FROM `scene_template` WHERE `SceneId`=233;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (233, 0, 519, '');
DELETE FROM `scene_template` WHERE `SceneId`=244;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (244, 25, 524, '');
DELETE FROM `scene_template` WHERE `SceneId`=254;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (254, 27, 541, '');
DELETE FROM `scene_template` WHERE `SceneId`=285;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (285, 0, 574, '');
DELETE FROM `scene_template` WHERE `SceneId`=286;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (286, 0, 578, '');
DELETE FROM `scene_template` WHERE `SceneId`=287;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (287, 0, 579, '');
DELETE FROM `scene_template` WHERE `SceneId`=288;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (288, 0, 580, '');
DELETE FROM `scene_template` WHERE `SceneId`=289;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (289, 0, 582, '');
DELETE FROM `scene_template` WHERE `SceneId`=290;
INSERT INTO `scene_template` (`SceneId`, `Flags`, `ScriptPackageID`, `ScriptName`) VALUES (290, 0, 581, '');
