DELETE FROM `access_requirement` WHERE `mapId`=999;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (999, 12, 85, 0, 0, 0, 0, 0, 0, NULL, 'Theramore\'s Fall Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1000;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1000, 12, 85, 0, 0, 0, 0, 0, 0, NULL, 'Theramore\'s Fall Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1005;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1005, 11, 90, 0, 0, 0, 0, 0, 0, NULL, 'A Brewing Storm Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1005;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1005, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'A Brewing Storm Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1014;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1014, 12, 99, 0, 0, 0, 0, 0, 0, NULL, 'Test Scenario PS Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1024;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1024, 11, 99, 0, 0, 0, 0, 0, 0, NULL, 'Greenstone Village Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1024;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1024, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Greenstone Village Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1030;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1030, 11, 90, 0, 0, 0, 0, 0, 0, NULL, 'Crypt of Forgotten Kings Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1030;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1030, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Crypt of Forgotten Kings Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1031;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1031, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Arena of Annihilation Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1035;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1035, 12, 99, 0, 0, 0, 0, 0, 0, NULL, 'Temple of Kotmogu Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1048;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1048, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Unga Ingoo Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1049;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1049, 12, 99, 99, 0, 0, 0, 0, 0, NULL, 'Crafty Test Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1050;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1050, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Assault on Zan\'vess Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1051;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1051, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Brewmoon Festival Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1095;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1095, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Dagger in the Dark Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1099;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1099, 11, 90, 0, 0, 0, 0, 0, 0, NULL, 'Battle on the High Seas Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1099;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1099, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Battle on the High Seas Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1102;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1102, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Domination Point Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1103;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1103, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Lion\'s Landing Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1104;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1104, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'A Little Patience Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1126;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1126, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Isle of Thunder Scenarios');
DELETE FROM `access_requirement` WHERE `mapId`=1130;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1130, 11, 90, 0, 0, 0, 0, 0, 0, NULL, 'Blood in the Snow Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1130;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1130, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Blood in the Snow Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1131;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1131, 11, 90, 0, 0, 0, 0, 0, 0, NULL, 'The Secrets of Ragefire Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1131;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1131, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'The Secrets of Ragefire Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1135;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1135, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Troves of the Thunder King Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1144;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1144, 11, 90, 0, 0, 0, 0, 0, 0, NULL, 'Dark Heart of Pandaria Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1144;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1144, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Dark Heart of Pandaria Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1148;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1148, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Proving Grounds Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1155;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1155, 12, 99, 0, 0, 0, 0, 0, 0, NULL, 'Prototype Scenario Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1157;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1157, 11, 90, 0, 0, 0, 0, 0, 0, NULL, 'Noodle Time Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1157;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1157, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Finding the Secret Ingredient Entrance');
DELETE FROM `access_requirement` WHERE `mapId`=1161;
INSERT INTO `access_requirement` (`mapId`, `difficulty`, `level_min`, `level_max`, `item`, `item2`, `quest_done_A`, `quest_done_H`, `completed_achievement`, `quest_failed_text`, `comment`) VALUES (1161, 12, 90, 0, 0, 0, 0, 0, 0, NULL, 'Celestial Tournament Entrance');
