DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=2;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (2, 'Scholomance', 199.876, 125.346, 138.43, 4.67748, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=262;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (262, 'Heroic Random (Wrath of the Lich King)', 0, 0, 0, 0, 180);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=300;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (300, 'Random Cataclysm', 0, 0, 0, 0, 226);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=301;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (301, 'Random Cataclysm Heroic', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=304;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (304, 'Grim Batol', 0, 0, 0, 0, 305);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=305;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (305, 'Halls of Origination', 0, 0, 0, 0, 305);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=319;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (319, 'The Vortex Pinnacle', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=320;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (320, 'The Stonecore', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=321;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (321, 'Halls of Origination', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=322;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (322, 'Grim Batol', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=323;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (323, 'Blackrock Caverns', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=324;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (324, 'Throne of the Tides', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=325;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (325, 'Lost City of the Tol\'vir', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=326;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (326, 'Deadmines', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=327;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (327, 'Shadowfang Keep', 0, 0, 0, 0, 329);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=334;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (334, 'Zul\'Gurub', 0, 0, 0, 0, 346);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=340;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (340, 'Zul\'Aman', 0, 0, 0, 0, 346);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=416;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (416, 'Siege of Wyrmrest Temple', 0, 0, 0, 0, 372);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=417;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (417, 'Fall of Deathwing', -1803.01, -2394.98, 341.354, 0.08857, 372);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=434;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (434, 'Random Hour of Twilight Heroic', 0, 0, 0, 0, 353);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=435;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (435, 'End Time', 0, 0, 0, 0, 353);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=437;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (437, 'Well of Eternity', 0, 0, 0, 0, 353);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=439;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (439, 'Hour of Twilight', 0, 0, 0, 0, 353);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=462;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (462, 'Random Mists of Pandaria Heroic', 0, 0, 0, 0, 435);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=463;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (463, 'Random Mists of Pandaria Dungeon', 0, 0, 0, 0, 358);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=468;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (468, 'Temple of the Jade Serpent', 0, 0, 0, 0, 435);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=469;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (469, 'Stormstout Brewery', 0, 0, 0, 0, 435);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=470;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (470, 'Shado-Pan Monastery', 0, 0, 0, 0, 435);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=471;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (471, 'Gate of the Setting Sun', 0, 0, 0, 0, 435);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=493;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (493, 'Random Mists of Pandaria Scenario', 0, 0, 0, 0, 425);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=519;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (519, 'Mogu\'Shan Palace', 0, 0, 0, 0, 435);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=526;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (526, 'Terrace of Endless Spring', 0, 0, 0, 0, 600);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=530;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (530, 'Nightmare of Shek\'zeer', 0, 0, 0, 0, 600);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=540;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (540, 'Temple of Kotmogu', 1780.47, 1602.67, 34.3169, 0, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=541;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (541, 'Test Scenario PS', 3823.02, 2008.73, 935.205, 0, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=554;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (554, 'Siege of Niuzao Temple', 0, 0, 0, 0, 435);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=617;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (617, 'Assault on Shaol\'mara', 5675.7, 6216.16, 13.0363, 0.773, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=618;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (618, 'To the Skies!', 6149.74, 5040.18, 36.8959, 3.15, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=620;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (620, 'Troves of the Thunder King', -299.333, 1209.97, 127.637, 0, 425);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=621;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (621, 'The Fall of Shan Bu', 6937.37, 5208.28, 66.0382, 0.756, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=630;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (630, 'Siege of Niuzao Temple', 0, 0, 0, 0, 393);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=641;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (641, 'Random Mists of Pandaria Heroic Scenario', 0, 0, 0, 0, 496);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=645;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (645, 'Greenstone Village (Heroic)', 2009.54, -2040.32, 221.069, 1.649, 496);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=658;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (658, 'Proving Grounds', 3756.82, 521.777, 639.692, 0, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=697;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (697, 'Prototype Scenario', -1649.03, -1803.77, 79.9783, 0, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=699;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (699, 'Crafty Test', 1513.28, 5352.51, 146.241, 0, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=701;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (701, 'Celestial Tournament', -611.283, -4993.77, -6.27734, 0, 425);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=728;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (728, 'Gates of Retribution', 1422.57, -4867.28, 11.79, 1.9, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=729;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (729, 'The Underhold', 1726.47, -4767.94, -242.28, 0.102, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=730;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (730, 'Downfall', 1964.21, -5190.32, -272.25, 3.721, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=745;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (745, 'Finding the Secret Ingredient', -262.642, 585.236, 167.548, 0, 0);
DELETE FROM `lfg_dungeon_template` WHERE `dungeonId`=749;
INSERT INTO `lfg_dungeon_template` (`dungeonId`, `name`, `position_x`, `position_y`, `position_z`, `orientation`, `requiredItemLevel`) VALUES (749, 'Noodle Time (heroic)', -262.642, 585.236, 167.548, 0, 496);
