DELETE FROM `instance_template` WHERE `map`=959;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (959, 870, 'instance_shadopan_monastery', 1);
DELETE FROM `instance_template` WHERE `map`=960;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (960, 870, 'instance_temple_of_jade_serpent', 1);
DELETE FROM `instance_template` WHERE `map`=961;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (961, 870, 'instance_stormstout_brewery', 1);
DELETE FROM `instance_template` WHERE `map`=962;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (962, 870, 'instance_gate_of_the_setting_sun', 1);
DELETE FROM `instance_template` WHERE `map`=994;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (994, 870, 'instance_mogu_shan_palace', 1);
DELETE FROM `instance_template` WHERE `map`=996;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (996, 870, 'instance_terrace_of_endless_spring', 1);
DELETE FROM `instance_template` WHERE `map`=999;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (999, 870, 'instance_fall_of_theramore_horde', 1);
DELETE FROM `instance_template` WHERE `map`=1000;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1000, 870, 'instance_fall_of_theramore_alliance', 0);
DELETE FROM `instance_template` WHERE `map`=1001;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1001, 870, 'instance_scarlet_halls', 1);
DELETE FROM `instance_template` WHERE `map`=1004;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1004, 0, 'instance_scarlet_monastery', 0);
DELETE FROM `instance_template` WHERE `map`=1005;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1005, 870, 'instance_brewing_storm', 1);
DELETE FROM `instance_template` WHERE `map`=1007;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1007, 0, 'instance_scholomance', 0);
DELETE FROM `instance_template` WHERE `map`=1008;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1008, 870, 'instance_mogu_shan_vault', 1);
DELETE FROM `instance_template` WHERE `map`=1009;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1009, 870, 'instance_heart_of_fear', 1);
DELETE FROM `instance_template` WHERE `map`=1011;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1011, 870, 'instance_siege_of_niuzao_temple', 1);
DELETE FROM `instance_template` WHERE `map`=1014;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1014, 870, '', 1);
DELETE FROM `instance_template` WHERE `map`=1024;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1024, 870, 'instance_greenstone_village', 1);
DELETE FROM `instance_template` WHERE `map`=1030;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1030, 870, 'instance_crypt_of_forgotten_kings', 1);
DELETE FROM `instance_template` WHERE `map`=1031;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1031, 870, 'instance_arena_of_annihiliation', 1);
DELETE FROM `instance_template` WHERE `map`=1035;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1035, 870, '', 1);
DELETE FROM `instance_template` WHERE `map`=1048;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1048, 870, 'instance_unga_ingoo', 1);
DELETE FROM `instance_template` WHERE `map`=1049;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1049, 870, '', 1);
DELETE FROM `instance_template` WHERE `map`=1050;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1050, 870, 'instance_assault_on_zanvess', 1);
DELETE FROM `instance_template` WHERE `map`=1051;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1051, 870, 'instance_brewmoon_festival', 1);
DELETE FROM `instance_template` WHERE `map`=1095;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1095, 870, 'instance_dagger_in_the_dark', 1);
DELETE FROM `instance_template` WHERE `map`=1098;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1098, 1064, 'instance_throne_of_thunder', 1);
DELETE FROM `instance_template` WHERE `map`=1099;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1099, 870, 'instance_battle_on_the_high_seas', 1);
DELETE FROM `instance_template` WHERE `map`=1102;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1102, 870, '', 1);
DELETE FROM `instance_template` WHERE `map`=1103;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1103, 870, '', 1);
DELETE FROM `instance_template` WHERE `map`=1104;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1104, 870, 'instance_little_patience', 1);
DELETE FROM `instance_template` WHERE `map`=1112;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1112, 0, 'instance_pursuing_the_black_harvest', 1);
DELETE FROM `instance_template` WHERE `map`=1126;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1126, 870, 'instance_isle_of_thunder', 1);
DELETE FROM `instance_template` WHERE `map`=1130;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1130, 870, 'instance_blood_in_the_snow', 1);
DELETE FROM `instance_template` WHERE `map`=1131;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1131, 870, 'instance_secrets_of_ragefire', 1);
DELETE FROM `instance_template` WHERE `map`=1135;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1135, 870, 'instance_thunder_king_citadel', 1);
DELETE FROM `instance_template` WHERE `map`=1136;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1136, 870, 'instance_siege_of_orgrimmar', 1);
DELETE FROM `instance_template` WHERE `map`=1144;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1144, 870, 'instance_dark_heart_of_pandaria', 1);
DELETE FROM `instance_template` WHERE `map`=1148;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1148, 870, 'instance_proving_grounds', 1);
DELETE FROM `instance_template` WHERE `map`=1155;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1155, 870, '', 1);
DELETE FROM `instance_template` WHERE `map`=1157;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1157, 870, 'instance_secret_ingridient', 1);
DELETE FROM `instance_template` WHERE `map`=1161;
INSERT INTO `instance_template` (`map`, `parent`, `script`, `allowMount`) VALUES (1161, 870, '', 1);
